#!/usr/bin/env bash
# SessionEnd hook — captures usage + writes in-flight handoff.
#
# in-flight.md is the bridge between sessions: when a session ends mid-feature,
# the next session reads it via session-start-context.sh to pick up where we left off.

set -uo pipefail

mkdir -p .claude/hooks/.log
ts=$(date -Iseconds)
printf '%s session end\n' "$ts" >> .claude/hooks/.log/session.log

# Round 6 B: graceful exit — delete heartbeat. If next session-start finds the
# heartbeat still present, it means the prior session was killed (no graceful
# SessionEnd ever fired) and we should surface a recovery banner.
rm -f .claude/memory/.cache/current-session.json

# ─── Initiative living state (memory-system review §7.2) ────────────────
# SessionEnd is a network boundary: rewrite initiatives/active/<id>.STATE.md
# and the .claude/state/current-{initiative,spec} pointers that the usage
# attribution below reads. LOUD on failure — memory-plane writes must not
# fail silently (§7.6).
if [ -x .claude/scripts/initiative-state.sh ]; then
  bash .claude/scripts/initiative-state.sh sync >/dev/null \
    || echo "session-end: initiative-state.sh sync FAILED — STATE.md and attribution pointers are stale" >&2
fi

# ─── Token usage via ccusage — Round 7 E: inject initiative + spec attribution
# Reads current initiative/spec from .claude/state/ written by initiative-state.sh
# (the load-bearing primitive that links sessions to roadmap items).
init_tag=""
spec_tag=""
[ -f .claude/state/current-initiative ] && init_tag=$(cat .claude/state/current-initiative | tr -d '\n' | head -c 32)
[ -f .claude/state/current-spec ] && spec_tag=$(cat .claude/state/current-spec | tr -d '\n' | head -c 32)

emit_ccusage() {
  local raw="$1"
  if command -v jq >/dev/null 2>&1 && [ -n "$raw" ]; then
    # JUSTIFIED: jq error muted — non-JSON ccusage output is passed through unmodified by the else-branch; merge failure shouldn't crash usage capture
    # (e2e-audit failure-recovery-2: comment moved ABOVE — inside the backslash
    # continuation it TERMINATED the command, severing the jq filter argument)
    printf '%s' "$raw" | jq -c \
      --arg init "$init_tag" \
      --arg spec "$spec_tag" \
      '. + {initiative: $init, spec: $spec}' 2>/dev/null
  else
    printf '%s\n' "$raw"
  fi
}

if command -v ccusage >/dev/null 2>&1; then
  # JUSTIFIED: ccusage error muted + empty fallback — token telemetry is optional; a failed/absent ccusage just yields empty raw, skipped by the [ -n "$raw" ] guard
  raw=$(ccusage blocks --json 2>/dev/null || echo "")
  [ -n "$raw" ] && emit_ccusage "$raw" >> .claude/hooks/.log/usage.jsonl
elif command -v npx >/dev/null 2>&1; then
  # JUSTIFIED: npx ccusage error muted + empty fallback — same optional-telemetry contract; empty raw is skipped by the guard
  raw=$(npx --no-install ccusage blocks --json 2>/dev/null || echo "")
  [ -n "$raw" ] && emit_ccusage "$raw" >> .claude/hooks/.log/usage.jsonl
fi

# ─── Round 5 C6: consolidated session-recent store ──────────────────────
# Previously: in-flight.md (markdown), checkpoints/*.md (witness briefs), and
# instincts/observations.jsonl all captured overlapping session-recent state.
# Now: one canonical .claude/memory/.cache/session-recent.json with structured
# fields, and in-flight.md is a human-readable projection of it.

mkdir -p .claude/memory/.cache
session_recent=".claude/memory/.cache/session-recent.json"
in_flight=".claude/memory/in-flight.md"

{
  echo "# In-flight at $ts"
  echo
  echo "_Auto-generated by session-end.sh. The next session reads this._"
  echo

  # Git: uncommitted work?
  if git rev-parse --git-dir >/dev/null 2>&1; then
    echo "## Git state"
    # JUSTIFIED: git error muted — a detached HEAD has no ref name; "unknown" is the documented brief fallback
    branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)
    echo "- branch: \`$branch\`"
    # JUSTIFIED: git error muted — inside the rev-parse success branch; residual noise just yields an empty dirty list (treated as clean)
    dirty=$(git status --porcelain 2>/dev/null | head -20)
    if [ -n "$dirty" ]; then
      echo "- dirty (top 20 entries):"
      echo '```'
      echo "$dirty"
      echo '```'
    else
      echo "- working tree: clean"
    fi
    # JUSTIFIED: git error muted — a branch with no upstream (@{u}) is expected locally; an empty result correctly omits the unpushed section
    unpushed=$(git log @{u}..HEAD --oneline 2>/dev/null | head -5)
    if [ -n "$unpushed" ]; then
      echo "- unpushed commits:"
      echo '```'
      echo "$unpushed"
      echo '```'
    fi
    echo
  fi

  # Tasks: in-progress
  if [ -f tasks/TASKS.md ]; then
    echo "## Tasks in flight"
    grep -nE '^- \[~\] T-[0-9]+' tasks/TASKS.md | head -10 || echo "_(none)_"
    echo
    echo "## Tasks blocked"
    grep -nE '^- \[b\] T-[0-9]+' tasks/TASKS.md | head -10 || echo "_(none)_"
    echo
  fi

  # Specs: in review or draft
  if [ -d specs/active ]; then
    echo "## Specs in draft/review"
    # JUSTIFIED: grep error muted — an empty specs/active (no glob match) is normal; "_(none)_" is the intended brief fallback
    grep -lE '^status: (draft|review)' specs/active/*.md 2>/dev/null | head -5 || echo "_(none)_"
    echo
  fi

  # Swarms: any active streams?
  if [ -d .swarms/streams ]; then
    echo "## Active swarm streams"
    # JUSTIFIED: ls error muted — an empty streams dir is normal; "_(none)_" is the intended brief fallback
    ls -1 .swarms/streams/ 2>/dev/null | head -10 || echo "_(none)_"
    echo
  fi

  # Recently touched files (last 30 min)
  echo "## Files touched in last 30 min"
  # JUSTIFIED: find error muted — unreadable subdirs during the walk emit noise that would corrupt the markdown brief; the file list is best-effort
  find . -path './.git' -prune -o -type f -mmin -30 -not -path './.claude/hooks/.log/*' -not -path './node_modules/*' -print 2>/dev/null | head -15
  echo

  echo "---"
  echo "_Cleared at the start of the next session by session-start-context.sh after it loads this brief._"
# JUSTIFIED: the brief-writing block's stderr is muted — a transient write failure must not abort SessionEnd; the [ -f .tmp ] guard below handles a missing file
} > "$in_flight.tmp" 2>/dev/null

# Hard 200-line cap so a long session can't poison the next session's context.
# Round 5 D2: token cost — uncapped brief was the worst-case leak.
if [ -f "$in_flight.tmp" ]; then
  head -n 200 "$in_flight.tmp" > "$in_flight"
  rm -f "$in_flight.tmp"
fi

# Also emit structured session-recent.json — single source of truth that future
# tooling (Graphify, /context-pack, etc.) can query without parsing markdown.
if command -v jq >/dev/null 2>&1 && git rev-parse --git-dir >/dev/null 2>&1; then
  # JUSTIFIED: git error muted — a detached HEAD has no ref name; "unknown" is the documented cache fallback
  branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)
  # JUSTIFIED: git error muted — already inside the rev-parse success branch; any residual noise just yields a 0 count
  dirty_count=$(git status --porcelain 2>/dev/null | wc -l | tr -d ' ')
  # JUSTIFIED: git error muted — no upstream configured (@{u}) is expected on local branches; 0 unpushed is correct then
  unpushed_count=$(git log @{u}..HEAD --oneline 2>/dev/null | wc -l | tr -d ' ')
  # grep -c prints 0 AND exits 1 on zero matches — `|| echo 0` would double-print
  # ("0\n0"), breaking --argjson below and silently skipping session-recent.json
  # (observed: the file was 0 bytes). Capture-then-default instead.
  # JUSTIFIED: grep stderr muted — a missing TASKS.md leaves the var empty, defaulted to 0
  in_progress=$(grep -cE '^- \[~\] T-[0-9]+' tasks/TASKS.md 2>/dev/null) || true
  in_progress="${in_progress:-0}"
  # JUSTIFIED: grep stderr muted — same capture-then-default contract
  blocked=$(grep -cE '^- \[b\] T-[0-9]+' tasks/TASKS.md 2>/dev/null) || true
  blocked="${blocked:-0}"
  # JUSTIFIED: ls + grep errors muted — no specs/active glob match means 0 drafts, the correct cache value
  drafts=$(ls specs/active/*.md 2>/dev/null | xargs grep -lE '^status: draft' 2>/dev/null | wc -l | tr -d ' ')
  # JUSTIFIED: ls error muted — absent streams dir means 0 active streams, the correct cache value
  streams=$(ls -1 .swarms/streams/ 2>/dev/null | wc -l | tr -d ' ')

  jq -nc \
    --arg ts "$ts" \
    --arg branch "$branch" \
    --argjson dirty "${dirty_count:-0}" \
    --argjson unpushed "${unpushed_count:-0}" \
    --argjson in_progress "${in_progress:-0}" \
    --argjson blocked "${blocked:-0}" \
    --argjson drafts "${drafts:-0}" \
    --argjson streams "${streams:-0}" \
    '{
      generated_at: $ts,
      git: {branch: $branch, dirty_count: $dirty, unpushed_count: $unpushed},
      tasks: {in_progress: $in_progress, blocked: $blocked},
      specs: {drafts: $drafts},
      swarm_streams: $streams
    # JUSTIFIED: the redirect drops jq stderr — the session-recent cache is advisory; a write hiccup must not fail the SessionEnd hook
    }' > "$session_recent" 2>/dev/null
fi

# Round 6 B: snapshot ~/.claude/projects/<slug>/ into the repo so subscription
# switches / home-dir wipes / new-machine clones are recoverable.
# Best-effort, non-blocking.
# JUSTIFIED: backgrounded best-effort mirror at exit — its stderr is irrelevant to the closing session and must not delay shutdown
bash .claude/scripts/mirror-user-state.sh 2>/dev/null &
# JUSTIFIED: guards disown on shells lacking the builtin; a non-job-control shell simply skips detaching, which is harmless at exit
disown 2>/dev/null || true

exit 0
