#!/usr/bin/env bash
# daily-briefing.sh — write a morning briefing of what shipped, WITH the verifiable
# artifacts that prove each claim (operator directive 2026-07-24: "attach the
# verifiable artifacts with proof how it said the initiative, spec and tasks are
# completed"). No unbacked assertions — every shipped line carries a link to the
# proof, and the proof's own verdict is quoted inline (§VII.8: no artifact = it
# didn't happen).
#
# Source: .claude/state/ship-log.jsonl (written by reconcile-shipped.sh). Output:
# docs/briefings/YYYY-MM-DD.md, then committed.
#
# Per shipped PR it emits, and PROVES:
#   - PR         → merge SHA + URL + the required-checks-green result (gh pr checks)
#   - Initiative → initiatives/**/<id>.STATE.md line showing `phase: shipped`
#   - Spec       → specs/**/<id>-*.md `status: shipped` + verify/**/evidence.json verdict
#   - Tasks      → the TASKS.md `[s]` line + its TDD ledger verify/<date>/T-<id>/{red,green}.log
#   - Decisions  → the Constraint/Rejected/Directive commit trailers (deduped)
#
# Usage:
#   daily-briefing.sh                 # today's briefing from the ship-log, commit it
#   daily-briefing.sh --date <ymd>    # briefing for a specific day
#   daily-briefing.sh --no-commit     # write the file, don't commit
# Test hooks: BRIEF_SHIP_LOG, BRIEF_OUT_DIR, BRIEF_DATE, BRIEF_REPO, BRIEF_NO_GH=1.
set -uo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

SHIP_LOG="${BRIEF_SHIP_LOG:-.claude/state/ship-log.jsonl}"
OUT_DIR="${BRIEF_OUT_DIR:-docs/briefings}"
DATE="${BRIEF_DATE:-$(date +%F)}"
COMMIT=1
while [ $# -gt 0 ]; do
  case "$1" in
    --date) DATE="${2:?}"; shift ;;
    --no-commit) COMMIT=0 ;;
    *) echo "daily-briefing: unknown arg '$1'"; exit 2 ;;
  esac
  shift
done

command -v jq >/dev/null 2>&1 || { echo "daily-briefing: jq required"; exit 5; }
mkdir -p "$OUT_DIR"
OUT="$OUT_DIR/$DATE.md"

# Records merged on DATE (mergedAt starts with the date). If the ship-log is
# absent/empty, still write an honest "nothing shipped" briefing (not silence).
records="[]"
if [ -f "$SHIP_LOG" ]; then
  records=$(jq -s --arg d "$DATE" '[.[] | select((.mergedAt // "") | startswith($d))]' "$SHIP_LOG" 2>/dev/null || echo '[]')
fi
n=$(printf '%s' "$records" | jq 'length')

# ── Proof helpers ────────────────────────────────────────────────────────
# Quote the verdict line out of an evidence.json (proof an AC bundle passed).
evidence_verdict() {
  local f="$1"
  [ -f "$f" ] || { printf 'MISSING (%s not found)' "$f"; return; }
  jq -r '"verdict=\(.verdict // "?") ac_proven=\(.ac_proven // "?")/\(.ac_total // "?") commit=\((.commit // "")[0:7])"' "$f" 2>/dev/null \
    || printf 'unreadable evidence at %s' "$f"
}
# Show the STATE.md phase line (proof an initiative is shipped).
state_phase_line() {
  local f="$1"
  [ -f "$f" ] || { printf 'MISSING'; return; }
  grep -iE '^phase:' "$f" 2>/dev/null | head -1 | sed 's/^/`/; s/$/`/'
}
# Does a task have BOTH red+green ledger logs? (proof of TDD, §VII.1)
task_ledger() {
  local t="$1"
  local hit
  hit=$(find verify -type d -name "$t" 2>/dev/null | head -1)
  if [ -n "$hit" ] && [ -f "$hit/red.log" ] && [ -f "$hit/green.log" ]; then
    printf '`%s/{red,green}.log` ✓' "$hit"
  elif [ -n "$hit" ]; then
    printf '`%s/` (partial ledger)' "$hit"
  else
    printf 'no ledger dir found for %s' "$t"
  fi
}

# ── Render ───────────────────────────────────────────────────────────────
{
  echo "# Daily briefing — $DATE"
  echo
  echo "> Generated by daily-briefing.sh from \`$SHIP_LOG\`. Every shipped claim below"
  echo "> links the artifact that proves it (evidence bundle verdict, STATE phase, TDD"
  echo "> ledger, merge SHA). Unbacked claims are marked ⚠ UNPROVEN."
  echo

  if [ "${n:-0}" -eq 0 ]; then
    echo "**Nothing shipped on $DATE.** No PRs merged (or the ship-log has no record for"
    echo "this date). If you expected a merge, check: CI status, the auto-merge label, and"
    echo "\`reconcile-shipped.sh\` ran after the merge."
  else
    echo "**$n PR(s) shipped.**"
    echo
    # Iterate records
    printf '%s' "$records" | jq -c '.[]' | while IFS= read -r rec; do
      pr=$(printf '%s' "$rec" | jq -r '.pr')
      title=$(printf '%s' "$rec" | jq -r '.title')
      url=$(printf '%s' "$rec" | jq -r '.url')
      sha=$(printf '%s' "$rec" | jq -r '.mergeCommit // ""')
      echo "## PR #$pr — $title"
      echo
      echo "- **Merged:** $(printf '%s' "$rec" | jq -r '.mergedAt') · commit \`${sha:0:12}\` · [$url]($url)"

      # PR proof: required checks green (queried live unless BRIEF_NO_GH).
      if [ "${BRIEF_NO_GH:-0}" != "1" ] && command -v gh >/dev/null 2>&1; then
        repo="${BRIEF_REPO:-$(gh repo view --json nameWithOwner --jq .nameWithOwner 2>/dev/null)}"
        checks=$(gh pr checks "$pr" --repo "$repo" --json bucket 2>/dev/null || echo '[]')
        pass=$(printf '%s' "$checks" | jq '[.[]|select(.bucket=="pass")]|length' 2>/dev/null || echo 0)
        tot=$(printf '%s' "$checks" | jq 'length' 2>/dev/null || echo 0)
        if [ "${tot:-0}" -gt 0 ] && [ "$pass" = "$tot" ]; then
          echo "- **CI proof:** all $tot required checks GREEN at merge ✓"
        else
          echo "- **CI proof:** ⚠ $pass/$tot checks green (merged without full green — see billing/override note)"
        fi
      fi
      echo

      # Initiatives
      inits=$(printf '%s' "$rec" | jq -r '.initiatives[]?')
      if [ -n "$inits" ]; then
        echo "### Initiatives shipped"
        printf '%s\n' "$inits" | while IFS= read -r ip; do
          [ -z "$ip" ] && continue
          echo "- \`$ip\` — proof: $(state_phase_line "$ip")"
        done
        echo
      fi

      # Specs (proof = status:shipped + evidence verdict)
      specs=$(printf '%s' "$rec" | jq -r '.specs[]?')
      if [ -n "$specs" ]; then
        echo "### Specs shipped"
        printf '%s\n' "$specs" | while IFS= read -r sp; do
          [ -z "$sp" ] && continue
          specfile=$(ls specs/*/"$sp"-*.md 2>/dev/null | head -1)
          statusline=""
          [ -n "$specfile" ] && statusline=$(grep -iE '^status:' "$specfile" 2>/dev/null | head -1)
          # matching evidence path from the record
          ev=$(printf '%s' "$rec" | jq -r --arg s "$sp" '.evidence[]? | select(test($s))' | head -1)
          echo "- **spec $sp** — \`${specfile:-spec file not found}\`${statusline:+ (\`$statusline\`)}"
          if [ -n "$ev" ]; then
            echo "  - proof: \`$ev\` → $(evidence_verdict "$ev")"
          else
            echo "  - ⚠ UNPROVEN: no evidence.json carries spec $sp"
          fi
        done
        echo
      fi

      # Tasks (proof = TDD ledger)
      tasks=$(printf '%s' "$rec" | jq -r '.tasks[]?')
      if [ -n "$tasks" ]; then
        echo "### Tasks shipped"
        printf '%s\n' "$tasks" | while IFS= read -r tk; do
          [ -z "$tk" ] && continue
          echo "- **$tk** — TDD ledger: $(task_ledger "$tk")"
        done
        echo
      fi

      # Decisions (deduped trailers)
      decs=$(printf '%s' "$rec" | jq -r '.decisions[]?' | sort -u | grep -iE '^(Constraint|Rejected|Directive):' || true)
      if [ -n "$decs" ]; then
        echo "### Key decisions"
        printf '%s\n' "$decs" | sed 's/^/- /'
        echo
      fi
    done
  fi

  echo "---"
  echo "_Proof policy: a claim without a linked, readable artifact is ⚠ UNPROVEN (constitution §VII.8)._"
} > "$OUT"

echo "daily-briefing: wrote $OUT ($n PR(s))"

if [ "$COMMIT" -eq 1 ]; then
  git add "$OUT" 2>/dev/null || true
  if git diff --cached --quiet -- "$OUT" 2>/dev/null; then
    echo "daily-briefing: no change to commit"
  else
    git commit -q -m "docs(briefing): $DATE shipped digest ($n PR)" \
      -m "Auto-generated morning briefing with per-claim proof artifacts." \
      -m "Co-Authored-By: Claude <noreply@anthropic.com>" 2>&1 | tail -1 || true
    echo "daily-briefing: committed $OUT"
  fi
fi
