#!/usr/bin/env bash
# memory-rollup.sh — multi-horizon episodic consolidation.
#
# Memory-system review (docs/research/memory-system-review.md §7.5): episodic
# memory evaporated after ~7 days (in-flight TTL, observation rotation) so a
# multi-year project loses its own history. This rolls each horizon up into the
# next at log-scale cost:
#
#   weekly    .claude/memory/rollups/YYYY-Www.md   (from git + session telemetry)
#   monthly   .claude/memory/rollups/YYYY-MM.md    (from that month's weeklies)
#   quarterly .claude/memory/rollups/YYYY-Qn.md    (from that quarter's monthlies)
#
# Each file is capped at 100 lines. Deterministic (no LLM): /dream may enrich
# the narrative afterwards, but the factual skeleton never depends on a model.
#
# Usage: memory-rollup.sh weekly|monthly|quarterly|auto
#   auto = weekly always; monthly/quarterly when their period has entries and
#          the rollup file doesn't exist yet (cron/dream-safe, idempotent).

set -uo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

# M-10-lock: all memory-plane writers share ONE lock so a backgrounded dream's
# rollup can't interleave with a live session's write and clobber a rollup file.
# shellcheck source=lib/with-lock.sh
. "$(dirname "$0")/lib/with-lock.sh"

RDIR=".claude/memory/rollups"
mkdir -p "$RDIR"

die() { echo "memory-rollup: $*" >&2; exit 1; }

cap_install() { # tmp final
  head -n 100 "$1" > "$2" && rm -f "$1" || die "failed installing $2"
}

cmd_weekly() {
  local week file tmp
  week=$(date +%G-W%V)
  file="$RDIR/${week}.md"
  tmp="${file}.tmp"

  {
    echo "# Rollup — week $week"
    echo
    echo "> Generated by memory-rollup.sh ($(date -Iseconds)). Horizon: 7 days."
    echo
    echo "## Commits this week"
    # JUSTIFIED: empty repo / no commits this week — empty section is the correct content
    git log --since='7 days ago' --oneline 2>/dev/null | head -25 | sed 's/^/- /' || true
    echo
    echo "## Tasks completed this week"
    # last_touched within the last 7 days, status [x]; T-guard avoids the template
    # line. Portable (no gawk 3-arg match): sed extracts "date task-id", awk filters.
    # JUSTIFIED: BSD-vs-GNU date probe — whichever flag form is unsupported errors silently and the other computes the cutoff
    cutoff=$(date -v-7d +%Y-%m-%d 2>/dev/null || date -d '7 days ago' +%Y-%m-%d)
    # JUSTIFIED: no completed tasks with a parseable last_touched — empty section is correct
    grep -E '^- \[x\] T-[0-9]+' tasks/TASKS.md 2>/dev/null \
      | sed -nE 's/^- \[x\] (T-[0-9]+).*last_touched: *([0-9]{4}-[0-9]{2}-[0-9]{2}).*/\2 \1/p' \
      | awk -v c="$cutoff" '$1 >= c {print "- " $2 " (" $1 ")"}' | head -15 || true
    echo
    echo "## Incidents / audits added"
    # JUSTIFIED: no new memory events this week — empty section is correct
    git log --since='7 days ago' --name-only --format='' 2>/dev/null \
      | grep -E '^\.claude/memory/(incidents|audits)/' | sort -u | sed 's/^/- /' || true
    echo
    echo "## Initiative state at week end"
    # JUSTIFIED: pre-sync repos have no STATE.md — placeholder is correct
    cat initiatives/active/*.STATE.md 2>/dev/null | grep -E '^\- \*\*(phase|tasks)\*\*' | head -6 || echo "_(no STATE.md yet)_"
  } > "$tmp" || die "failed writing $tmp"
  # M-10-lock: serialize the tracked-file install against a concurrent memory-plane writer.
  with_lock "memory-plane" cap_install "$tmp" "$file"
  echo "memory-rollup: wrote $file"
}

# Aggregate a set of child rollups into one parent file: header lines + per-child
# one-line digest (first "## Commits" count + tasks count), then key bullets.
aggregate() { # parent_file title child_glob...
  local parent="$1" title="$2"; shift 2
  local tmp="${parent}.tmp" child
  {
    echo "# Rollup — $title"
    echo
    echo "> Generated by memory-rollup.sh ($(date -Iseconds)). Aggregates: $*"
    echo
    for child in "$@"; do
      [ -f "$child" ] || continue
      echo "## $(basename "$child" .md)"
      # commit lines + completed-task lines from the child, compressed
      awk '/^## Commits/{c=1;next} /^## Tasks completed/{c=0;t=1;next} /^## /{t=0}
           c && /^- /{cc++} t && /^- /{tt++; if (tt<=5) buf=buf "\n  " $0}
           END{printf "- %d commits, %d tasks completed%s\n", cc+0, tt+0, buf}' "$child"
    done
  } > "$tmp" || die "failed writing $tmp"
  # M-10-lock: serialize the tracked-file install against a concurrent memory-plane writer.
  with_lock "memory-plane" cap_install "$tmp" "$parent"
  echo "memory-rollup: wrote $parent"
}

cmd_monthly() {
  local month file
  month=$(date +%Y-%m)
  file="$RDIR/${month}.md"
  # children: weeklies whose ISO week falls in this month — approximate by mtime month
  # JUSTIFIED: zero weeklies this month — find yields nothing and we no-op below
  local children
  children=$(find "$RDIR" -name "$(date +%G)-W*.md" -newermt "$(date +%Y-%m-01)" 2>/dev/null | sort)
  [ -z "$children" ] && { echo "memory-rollup: no weeklies for $month — skipped"; return 0; }
  # shellcheck disable=SC2086  # JUSTIFICATION: children is a newline list of our own filenames (no spaces) ISSUE: #0
  aggregate "$file" "month $month" $children
}

cmd_quarterly() {
  local q y file months
  y=$(date +%Y)
  case "$(date +%m)" in
    01|02|03) q=1 ;; 04|05|06) q=2 ;; 07|08|09) q=3 ;; *) q=4 ;;
  esac
  file="$RDIR/${y}-Q${q}.md"
  # JUSTIFIED: zero monthlies this quarter — no-op below is correct
  months=$(ls "$RDIR/${y}"-0[1-9].md "$RDIR/${y}"-1[0-2].md 2>/dev/null | sort | tail -3)
  [ -z "$months" ] && { echo "memory-rollup: no monthlies for ${y}-Q${q} — skipped"; return 0; }
  # shellcheck disable=SC2086  # JUSTIFICATION: months is a newline list of our own filenames (no spaces) ISSUE: #0
  aggregate "$file" "quarter ${y}-Q${q}" $months
}

cmd_auto() {
  cmd_weekly
  # Idempotent: only build parent horizons when absent (cron/dream re-runs are safe)
  [ -f "$RDIR/$(date +%Y-%m).md" ] || cmd_monthly
  local y q
  y=$(date +%Y)
  case "$(date +%m)" in 01|02|03) q=1 ;; 04|05|06) q=2 ;; 07|08|09) q=3 ;; *) q=4 ;; esac
  [ -f "$RDIR/${y}-Q${q}.md" ] || cmd_quarterly
}

case "${1:-}" in
  weekly) cmd_weekly ;;
  monthly) cmd_monthly ;;
  quarterly) cmd_quarterly ;;
  auto) cmd_auto ;;
  *) echo "usage: memory-rollup.sh weekly|monthly|quarterly|auto" >&2; exit 1 ;;
esac
