#!/usr/bin/env bash
# memory-rollup.sh — multi-horizon episodic consolidation.
#
# Memory-system review (docs/research/memory-system-review.md §7.5): episodic
# memory evaporated after ~7 days (in-flight TTL, observation rotation) so a
# multi-year project loses its own history. This rolls each horizon up into the
# next at log-scale cost:
#
#   weekly    .claude/memory/rollups/YYYY-Www.md   (from git + session telemetry)
#   monthly   .claude/memory/rollups/YYYY-MM.md    (from that month's weeklies)
#   quarterly .claude/memory/rollups/YYYY-Qn.md    (from that quarter's monthlies)
#
# Each file is capped at 100 lines. Deterministic (no LLM): /dream may enrich
# the narrative afterwards, but the factual skeleton never depends on a model.
#
# Usage: memory-rollup.sh weekly|monthly|quarterly|auto
#   auto = weekly always; monthly/quarterly when their period has entries and
#          the rollup file doesn't exist yet (cron/dream-safe, idempotent).

set -uo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

# M-10-lock: all memory-plane writers share ONE lock so a backgrounded dream's
# rollup can't interleave with a live session's write and clobber a rollup file.
# shellcheck source=lib/with-lock.sh
. "$(dirname "$0")/lib/with-lock.sh"

RDIR=".claude/memory/rollups"
mkdir -p "$RDIR"

die() { echo "memory-rollup: $*" >&2; exit 1; }

cap_install() { # tmp final
  head -n 100 "$1" > "$2" && rm -f "$1" || die "failed installing $2"
}

# M-18: resolve a target week to git-log range bounds. Accepts an explicit
# YYYY-Www (arg or $1), else ROLLUP_NOW epoch, else wall-clock. Echoes
# "<week> <since-iso> <until-iso> <cutoff-date>" so cmd_weekly derives ALL its
# time bounds from ONE source — making backfill of past weeks rig-testable
# without waiting real weeks (the arg was previously ignored entirely).
_week_bounds() {
  local want="${1:-}" epoch wk sy sm sd
  if printf '%s' "$want" | grep -qE '^[0-9]{4}-W[0-9]{2}$'; then
    wk="$want"
    # Monday of that ISO week → epoch (GNU: -d 'YYYY-Www-1'; BSD: manual).
    # JUSTIFIED: GNU path first; BSD strptime lacks %G%V, so fall back to a mid-week
    # anchor good enough for a 7-day git window and the human-readable heading.
    epoch=$(date -d "${wk}-1" +%s 2>/dev/null || echo "")
    if [ -z "$epoch" ]; then
      # BSD: approximate — Jan 4 is always in W01; add (week-1)*7 days.
      sy="${wk%%-*}"; local wn="${wk##*W}"
      epoch=$(date -j -f '%Y-%m-%d' "${sy}-01-04" +%s 2>/dev/null || echo 0)
      epoch=$(( epoch + (10#$wn - 1) * 604800 ))
    fi
  else
    epoch="${ROLLUP_NOW:-$(date +%s)}"
    # JUSTIFIED: GNU vs BSD week-format probe
    wk=$(date -d "@$epoch" +%G-W%V 2>/dev/null || date -r "$epoch" +%G-W%V 2>/dev/null || date +%G-W%V)
  fi
  local since until cutoff
  since=$(date -d "@$((epoch - 0))" +%Y-%m-%d 2>/dev/null || date -r "$epoch" +%Y-%m-%d 2>/dev/null || date +%Y-%m-%d)
  until=$(date -d "@$((epoch + 604800))" +%Y-%m-%d 2>/dev/null || date -r "$((epoch + 604800))" +%Y-%m-%d 2>/dev/null || echo "$since")
  cutoff="$since"
  echo "$wk $since $until $cutoff"
}

cmd_weekly() {
  local target="${1:-}" week file tmp since until cutoff bounds
  bounds=$(_week_bounds "$target")
  week=$(echo "$bounds" | awk '{print $1}')
  since=$(echo "$bounds" | awk '{print $2}')
  until=$(echo "$bounds" | awk '{print $3}')
  cutoff=$(echo "$bounds" | awk '{print $4}')
  file="$RDIR/${week}.md"
  tmp="${file}.tmp"

  {
    echo "# Rollup — week $week"
    echo
    echo "> Generated by memory-rollup.sh ($(date -Iseconds)). Horizon: 7 days (${since}..${until})."
    echo
    echo "## Commits this week"
    # M-18: range is derived from the target week, not a fixed "7 days ago".
    # JUSTIFIED: empty repo / no commits in range — empty section is the correct content
    git log --since="$since" --until="$until" --oneline 2>/dev/null | head -25 | sed 's/^/- /' || true
    echo
    echo "## Tasks completed this week"
    # last_touched within the target week, status [x]; T-guard avoids the template
    # line. Portable (no gawk 3-arg match): sed extracts "date task-id", awk filters.
    # JUSTIFIED: no completed tasks with a parseable last_touched — empty section is correct
    grep -E '^- \[x\] T-[0-9]+' tasks/TASKS.md 2>/dev/null \
      | sed -nE 's/^- \[x\] (T-[0-9]+).*last_touched: *([0-9]{4}-[0-9]{2}-[0-9]{2}).*/\2 \1/p' \
      | awk -v c="$cutoff" '$1 >= c {print "- " $2 " (" $1 ")"}' | head -15 || true
    echo
    echo "## Incidents / audits added"
    # M-18: same target-week range as the commits section.
    # JUSTIFIED: no new memory events this week — empty section is correct
    git log --since="$since" --until="$until" --name-only --format='' 2>/dev/null \
      | grep -E '^\.claude/memory/(incidents|audits)/' | sort -u | sed 's/^/- /' || true
    echo
    echo "## Initiative state at week end"
    # JUSTIFIED: pre-sync repos have no STATE.md — placeholder is correct
    cat initiatives/active/*.STATE.md 2>/dev/null | grep -E '^\- \*\*(phase|tasks)\*\*' | head -6 || echo "_(no STATE.md yet)_"
  } > "$tmp" || die "failed writing $tmp"
  # M-10-lock: serialize the tracked-file install against a concurrent memory-plane writer.
  with_lock "memory-plane" cap_install "$tmp" "$file"
  echo "memory-rollup: wrote $file"
}

# Aggregate a set of child rollups into one parent file: header lines + per-child
# one-line digest (first "## Commits" count + tasks count), then key bullets.
aggregate() { # parent_file title child_glob...
  local parent="$1" title="$2"; shift 2
  local tmp="${parent}.tmp" child
  {
    echo "# Rollup — $title"
    echo
    echo "> Generated by memory-rollup.sh ($(date -Iseconds)). Aggregates: $*"
    echo
    for child in "$@"; do
      [ -f "$child" ] || continue
      echo "## $(basename "$child" .md)"
      # commit lines + completed-task lines from the child, compressed
      awk '/^## Commits/{c=1;next} /^## Tasks completed/{c=0;t=1;next} /^## /{t=0}
           c && /^- /{cc++} t && /^- /{tt++; if (tt<=5) buf=buf "\n  " $0}
           END{printf "- %d commits, %d tasks completed%s\n", cc+0, tt+0, buf}' "$child"
    done
  } > "$tmp" || die "failed writing $tmp"
  # M-10-lock: serialize the tracked-file install against a concurrent memory-plane writer.
  with_lock "memory-plane" cap_install "$tmp" "$parent"
  echo "memory-rollup: wrote $parent"
}

cmd_monthly() {
  local month file
  month=$(date +%Y-%m)
  file="$RDIR/${month}.md"
  # children: weeklies whose ISO week falls in this month — approximate by mtime month
  # JUSTIFIED: zero weeklies this month — find yields nothing and we no-op below
  local children
  children=$(find "$RDIR" -name "$(date +%G)-W*.md" -newermt "$(date +%Y-%m-01)" 2>/dev/null | sort)
  [ -z "$children" ] && { echo "memory-rollup: no weeklies for $month — skipped"; return 0; }
  # shellcheck disable=SC2086  # JUSTIFICATION: children is a newline list of our own filenames (no spaces) ISSUE: #0
  aggregate "$file" "month $month" $children
}

cmd_quarterly() {
  local q y file months
  y=$(date +%Y)
  case "$(date +%m)" in
    01|02|03) q=1 ;; 04|05|06) q=2 ;; 07|08|09) q=3 ;; *) q=4 ;;
  esac
  file="$RDIR/${y}-Q${q}.md"
  # JUSTIFIED: zero monthlies this quarter — no-op below is correct
  months=$(ls "$RDIR/${y}"-0[1-9].md "$RDIR/${y}"-1[0-2].md 2>/dev/null | sort | tail -3)
  [ -z "$months" ] && { echo "memory-rollup: no monthlies for ${y}-Q${q} — skipped"; return 0; }
  # shellcheck disable=SC2086  # JUSTIFICATION: months is a newline list of our own filenames (no spaces) ISSUE: #0
  aggregate "$file" "quarter ${y}-Q${q}" $months
}

cmd_auto() {
  cmd_weekly
  # Idempotent: only build parent horizons when absent (cron/dream re-runs are safe)
  [ -f "$RDIR/$(date +%Y-%m).md" ] || cmd_monthly
  local y q
  y=$(date +%Y)
  case "$(date +%m)" in 01|02|03) q=1 ;; 04|05|06) q=2 ;; 07|08|09) q=3 ;; *) q=4 ;; esac
  [ -f "$RDIR/${y}-Q${q}.md" ] || cmd_quarterly
}

# M-18: iterate every ISO week from <start> to <end> inclusive, emitting each.
# Portable week arithmetic via epoch stepping (Monday anchor + 7-day strides).
cmd_backfill() {
  local start="$1" end="$2" e_start e_end e wk
  { printf '%s' "$start" | grep -qE '^[0-9]{4}-W[0-9]{2}$' && \
    printf '%s' "$end"   | grep -qE '^[0-9]{4}-W[0-9]{2}$'; } \
    || die "backfill <YYYY-Www> <YYYY-Www>"
  # Resolve both endpoints to epochs via the same bounds helper (its 2nd field is
  # the week's start date).
  e_start=$(date -d "$(_week_bounds "$start" | awk '{print $2}')" +%s 2>/dev/null \
            || date -j -f '%Y-%m-%d' "$(_week_bounds "$start" | awk '{print $2}')" +%s)
  e_end=$(date -d "$(_week_bounds "$end" | awk '{print $2}')" +%s 2>/dev/null \
          || date -j -f '%Y-%m-%d' "$(_week_bounds "$end" | awk '{print $2}')" +%s)
  [ "$e_start" -le "$e_end" ] || die "backfill: start week after end week"
  e="$e_start"
  while [ "$e" -le "$e_end" ]; do
    wk=$(date -d "@$e" +%G-W%V 2>/dev/null || date -r "$e" +%G-W%V)
    cmd_weekly "$wk"
    e=$(( e + 604800 ))
  done
}

case "${1:-}" in
  weekly) cmd_weekly "${2:-}" ;;   # M-18: optional target week arg
  monthly) cmd_monthly ;;
  quarterly) cmd_quarterly ;;
  auto) cmd_auto ;;
  backfill) cmd_backfill "${2:-}" "${3:-}" ;;   # M-18: weekly range backfill
  *) echo "usage: memory-rollup.sh weekly [YYYY-Www]|monthly|quarterly|auto|backfill <start> <end>" >&2; exit 1 ;;
esac
