#!/usr/bin/env bash
# Regenerate .claude/skills/REGISTRY.md — auto-discovery index of all skills.
# Round 9 F. Called from post-write-format.sh on SKILL.md changes.

set -uo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

OUT=".claude/skills/REGISTRY.md"

{
  echo "# Skill Registry"
  echo
  echo "_Auto-generated by .claude/scripts/regen-skill-registry.sh — do not hand-edit._"
  echo "_Last generated: $(date -Iseconds)_"
  echo
  echo "| Skill | Description | Auto-invoke | Model |"
  echo "|---|---|---|---|"

  for d in .claude/skills/*/; do
    skill_md="${d}SKILL.md"
    [ -f "$skill_md" ] || continue
    name=$(grep -E '^name:' "$skill_md" | head -1 | sed 's/name:[[:space:]]*//' | tr -d '"' | head -c 32)
    desc=$(grep -E '^description:' "$skill_md" | head -1 | sed 's/description:[[:space:]]*//' | tr -d '"' | head -c 120)
    model=$(grep -E '^model:' "$skill_md" | head -1 | sed 's/model:[[:space:]]*//' | tr -d '"' | head -c 16)
    [ -z "$model" ] && model="inherit"
    dmi=$(grep -E '^disable-model-invocation:' "$skill_md" | head -1 | sed 's/disable-model-invocation:[[:space:]]*//' | tr -d '"' | head -c 8)
    if [ "$dmi" = "true" ]; then
      invoke="no (operator-only)"
    else
      invoke="auto"
    fi
    printf "| \`%s\` | %s | %s | %s |\n" "$name" "$desc" "$invoke" "$model"
  done

  echo
  echo "## Stack mapping (for stack-aware suggestions)"
  echo
  cat <<'STACKMAP'
Atlas-detected stack → recommended skills:

- Vite + React → react-vite, front-end-design, tailwind-discipline
- Next.js (any router) → nextjs, front-end-design, tailwind-discipline
- React + Express/Fastify/Hono → react-node
- React + tRPC → react-node
- FastAPI → fastapi
- Flask + SocketIO → flask-realtime
- Any UI stack → typography, animation-discipline (load on need)
STACKMAP
} > "$OUT"

echo "✓ Regenerated $OUT ($(grep -c '^| `' "$OUT") skills)"

# ─── Gap-audit G14/G15: generated trigger table for skill-router.sh ─────
# Derives phrase→skill triggers from each skill's frontmatter (quoted phrases
# in when_to_use/description) plus any <skill>/triggers.yml (skill-creator
# contract — previously a dead artifact). Router loads this TSV at hook time,
# so coverage tracks the catalogue automatically.
TRIGGERS_OUT=".claude/state/skill-triggers.tsv"
mkdir -p "$(dirname "$TRIGGERS_OUT")"
{
  for d in .claude/skills/*/; do
    skill_md="${d}SKILL.md"
    [ -f "$skill_md" ] || continue
    sname=$(basename "$d")
    # quoted phrases out of when_to_use + description frontmatter lines
    grep -E '^(when_to_use|description):' "$skill_md" | head -2 \
      | grep -oE '"[^"]{4,60}"' | tr -d '"' \
      | tr '[:upper:]' '[:lower:]' \
      | while IFS= read -r phrase; do printf '%s\t%s\n' "$sname" "$phrase"; done
    # explicit triggers.yml (skill-creator contract)
    if [ -f "${d}triggers.yml" ]; then
      grep -E '^[[:space:]]*-[[:space:]]*' "${d}triggers.yml" \
        | sed -E 's/^[[:space:]]*-[[:space:]]*//; s/^["'\'']//; s/["'\'']$//' \
        | tr '[:upper:]' '[:lower:]' \
        | while IFS= read -r phrase; do
            [ "${#phrase}" -ge 4 ] && printf '%s\t%s\n' "$sname" "$phrase"
          done
    fi
  done
} | sort -u > "$TRIGGERS_OUT"

echo "✓ Regenerated $TRIGGERS_OUT ($(wc -l < "$TRIGGERS_OUT" | tr -d ' ') triggers)"
