#!/usr/bin/env bash
# shipped-registry.sh — M-08. Build specs/SHIPPED.md, a durable registry of what
# has actually shipped, from the evidence bundles under verify/**. Proof was
# rotting in 32 dated dirs with no index; this indexes them with latest-verdict-
# wins so "is spec-004 shipped?" has one authoritative answer.
#
#   bash .claude/scripts/shipped-registry.sh          # regenerate specs/SHIPPED.md
#   bash .claude/scripts/shipped-registry.sh --check   # exit 1 if out of date (CI)
#
# Source of truth per shipped spec = the NEWEST evidence.json (by generated_at)
# that carries that spec id. Merge/PR info is joined from git log by commit.
set -uo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

OUT="specs/SHIPPED.md"
MODE="${1:-write}"

# Collect one row per spec: newest evidence.json wins.
# TSV: spec \t generated_at \t commit \t verdict \t ac_proven/ac_total \t bundle_dir
rows=$(
  find verify -name 'evidence.json' -type f 2>/dev/null | while read -r ej; do
    # JUSTIFIED: a malformed bundle yields empty spec and is skipped below
    spec=$(jq -r '.spec // empty' "$ej" 2>/dev/null)
    [ -z "$spec" ] && continue
    gen=$(jq -r '.generated_at // ""' "$ej" 2>/dev/null)
    commit=$(jq -r '.commit // ""' "$ej" 2>/dev/null)
    verdict=$(jq -r '.verdict // "UNKNOWN"' "$ej" 2>/dev/null)
    acp=$(jq -r '.ac_proven // 0' "$ej" 2>/dev/null)
    act=$(jq -r '.ac_total // 0' "$ej" 2>/dev/null)
    # Use a rare literal delimiter (|) between fields — evidence values never
    # contain it, and it survives sort/awk/read far more reliably than a raw tab.
    # Empty gen/commit (spec-002 has null) render as blank fields, not shifts.
    printf '%s|%s|%s|%s|%s/%s|%s\n' "$spec" "${gen:-}" "${commit:-}" "$verdict" "$acp" "$act" "$(dirname "$ej")"
  done | sort -t'|' -k1,1 -k2,2r
)

# Keep only the newest row per spec (first after the reverse-time sort).
newest=$(printf '%s\n' "$rows" | awk -F'|' 'NF && !seen[$1]++')

# Render the registry. Join PR/merge info from git log by commit (best-effort).
render() {
  echo "# SHIPPED registry"
  echo
  echo "> Auto-generated by \`.claude/scripts/shipped-registry.sh\` from the evidence"
  echo "> bundles under \`verify/**/evidence.json\` (latest verdict per spec wins)."
  echo "> Do not hand-edit between the markers. \`tasks/TASKS.md\` remains the sole"
  echo "> source of task state; this is the durable shipped-proof index."
  echo
  echo "<!-- BEGIN:shipped-registry (generated) -->"
  echo
  echo "| Spec | Verdict | AC proven | Shipped (evidence) | Commit | PR / merge |"
  echo "| ---- | ------- | --------- | ------------------ | ------ | ---------- |"
  if [ -z "$newest" ]; then
    echo "| _(no evidence bundles found)_ | | | | | |"
  else
    printf '%s\n' "$newest" | while IFS='|' read -r spec gen commit verdict ac bundle; do
      [ -z "$spec" ] && continue
      short="${commit:0:9}"
      # Best-effort PR/subject from git log for this commit.
      pr=""
      if [ -n "$commit" ]; then
        subj=$(git log -1 --format='%s' "$commit" 2>/dev/null || true)
        # Extract a (#NN) PR number if present
        prnum=$(printf '%s' "$subj" | grep -oE '#[0-9]+' | head -1 || true)
        pr="${prnum:-—}"
      fi
      day="${gen%%T*}"
      printf '| %s | %s | %s | %s (%s) | %s | %s |\n' \
        "$spec" "$verdict" "$ac" "$day" "$bundle" "${short:-—}" "${pr:-—}"
    done
  fi
  echo
  echo "<!-- END:shipped-registry -->"
}

if [ "$MODE" = "--check" ]; then
  new=$(render)
  if [ -f "$OUT" ] && [ "$new" = "$(cat "$OUT")" ]; then
    echo "SHIPPED.md up to date"
    exit 0
  fi
  echo "SHIPPED.md is stale — run: bash .claude/scripts/shipped-registry.sh" >&2
  exit 1
fi

render > "$OUT"
echo "wrote $OUT ($(printf '%s\n' "$newest" | grep -c . ) spec rows)"
