#!/usr/bin/env bash
# trace-mismatch.sh — spec:005 AC-4 (gap G4). Surface where specs/SHIPPED.md
# records a spec as FAIL/UNPROVEN but that spec's tasks in tasks/TASKS.md all
# read terminal-done ([x]/[s]) — the current 001/002 disagreement. Traceability
# is only real if "shipped proof" and "task state" agree.
#
#   bash .claude/scripts/trace-mismatch.sh           # advisory: print findings, exit 0
#   bash .claude/scripts/trace-mismatch.sh --check    # exit 1 if any TRACE-MISMATCH
#
# For each spec row in SHIPPED.md (generated by shipped-registry.sh, a pipe table
# between the BEGIN/END markers):
#   - verdict FAIL|UNPROVEN + all its spec:<id> tasks done  → TRACE-MISMATCH (real
#     disagreement; --check fails on it).
#   - verdict PASS          + some of its tasks still pending → TRACE-INFO (inverse;
#     informational only, never fails).
# A spec with zero referencing tasks in TASKS.md is skipped (nothing to reconcile).
#
# Test hooks: TRACE_SHIPPED (path to SHIPPED.md), TRACE_TASKS (path to TASKS.md).
set -uo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

SHIPPED="${TRACE_SHIPPED:-specs/SHIPPED.md}"
TASKS="${TRACE_TASKS:-tasks/TASKS.md}"

CHECK=0
while [ $# -gt 0 ]; do
  case "$1" in
    --check) CHECK=1 ;;
    *) echo "trace-mismatch: unknown arg '$1'" >&2; exit 2 ;;
  esac
  shift
done

[ -f "$SHIPPED" ] || { echo "trace-mismatch: no SHIPPED.md ($SHIPPED)"; exit 0; }
[ -f "$TASKS" ]   || { echo "trace-mismatch: no TASKS.md ($TASKS)"; exit 0; }

# Returns: 0 = has >=1 referencing task AND all are terminal-done; else 1.
# Echoes "total open" so the caller can classify PASS-with-pending too.
spec_task_state() {
  local id="$1"
  local total open
  total=$(grep -cE "spec:${id}([^0-9]|$)" "$TASKS" 2>/dev/null) || true
  total="${total:-0}"
  open=$(grep -E "spec:${id}([^0-9]|$)" "$TASKS" 2>/dev/null \
    | grep -cE '^- \[( |~|!|b)\]') || true
  open="${open:-0}"
  printf '%s %s\n' "$total" "$open"
}

found_mismatch=0

# Parse the pipe-table rows: "| <spec> | <verdict> | ...". Skip header/separator
# rows (spec col not all-digits). Read spec + verdict from columns 2 and 3.
while IFS='|' read -r _ c_spec c_verdict _rest; do
  spec="$(printf '%s' "$c_spec" | tr -d '[:space:]')"
  verdict="$(printf '%s' "$c_verdict" | tr -d '[:space:]')"
  case "$spec" in ''|*[!0-9]*) continue ;; esac   # header/separator/non-id rows

  read -r total open < <(spec_task_state "$spec")
  [ "$total" -gt 0 ] || continue   # no tasks reference this spec → nothing to reconcile

  case "$verdict" in
    FAIL|UNPROVEN)
      if [ "$open" -eq 0 ]; then
        echo "TRACE-MISMATCH: spec $spec — tasks done but evidence verdict=$verdict"
        found_mismatch=1
      fi
      ;;
    PASS)
      if [ "$open" -gt 0 ]; then
        echo "TRACE-INFO: spec $spec — evidence verdict=PASS but $open task(s) still pending"
      fi
      ;;
  esac
done < "$SHIPPED"

if [ "$found_mismatch" -eq 0 ]; then
  echo "trace-mismatch: no TRACE-MISMATCH (SHIPPED verdicts agree with task state)"
fi

[ "$CHECK" -eq 1 ] && [ "$found_mismatch" -eq 1 ] && exit 1
exit 0
