import subprocess,json,hashlib,pathlib,collections,shutil,os
root=pathlib.Path(__file__).resolve().parents[3]; out=pathlib.Path('/tmp/claude-init-full-audit-reproduction'); out.mkdir(parents=True,exist_ok=True)
tmp=pathlib.Path('/tmp/claude-init-full-audit')
files=subprocess.check_output(['git','ls-files','-z'],cwd=root).decode().split('\0')[:-1]
rows=[]
for name in files:
 p=root/name; data=p.read_bytes(); checks={}
 if p.suffix=='.json':
  try:json.loads(data); checks['json']='pass'
  except Exception as e: checks['json']=str(e)
 if p.suffix=='.sh':
  r=subprocess.run(['bash','-n',str(p)],capture_output=True,text=True); checks['bash_syntax']='pass' if not r.returncode else r.stderr
 category='historical-evidence' if name.startswith(('verify/','tasks/archive/','specs/archive/','plans/archive/','.claude/memory.proposed/patches/')) else ('operational' if p.suffix in ('.sh','.py','.ts','.yml','.yaml','.json') else 'instructions-config-docs')
 rows.append({'path':name,'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest(),'category':category,'checks':checks})
manifest={'scope':'All git-tracked files at audit time; working-tree bytes, including five pre-existing modified initiative states. Excludes ignored runtime files and newly created audit documents. Categories are review routing, not proof of individual manual semantic review.','head':subprocess.check_output(['git','rev-parse','HEAD'],cwd=root).decode().strip(),'count':len(rows),'categories':dict(collections.Counter(r['category'] for r in rows)),'files':rows}
(out/'inventory.json').write_text(json.dumps(manifest,indent=2)+'\n')
# Live snapshots and original suite outputs are not regenerated by this script.
sh=(r['path'] for r in rows if r['path'].endswith('.sh') and not r['path'].startswith('verify/'))
r=subprocess.run(['shellcheck','-S','warning','-f','json',*list(sh)],cwd=root,capture_output=True,text=True)
(out/'shellcheck.json').write_text(r.stdout or '[]\n')
# Safe failure-injection fixtures: no real scanner, model, remote or deployment invoked.
fixture=tmp/'repro';fixture.mkdir(exist_ok=True);(fixture/'.claude/scripts/lib').mkdir(parents=True,exist_ok=True);(fixture/'specs/active').mkdir(parents=True,exist_ok=True);(fixture/'bin').mkdir(exist_ok=True)
for f in ['local-pr-check.sh','collect-evidence.sh','contract-tests.sh','spec-match.sh','lib/atomic-write.sh']:shutil.copyfile(root/'.claude/scripts'/f,fixture/'.claude/scripts'/f)
(fixture/'.claude/scripts/verify.sh').write_text('#!/bin/bash\nexit 0\n');(fixture/'bin/semgrep').write_text('#!/bin/bash\necho intentional-scanner-failure >&2\nexit 42\n');(fixture/'bin/semgrep').chmod(0o755)
env={**os.environ,'PATH':str(fixture/'bin')+':'+os.environ['PATH']};repros=[]
def run(label,args,cwd=fixture):
 r=subprocess.run(args,cwd=cwd,env=env,capture_output=True,text=True);repros.append({'name':label,'command':args,'exit_code':r.returncode,'stdout':r.stdout,'stderr':r.stderr});return r
run('Scanner exits 42 but local check passes',['bash','.claude/scripts/local-pr-check.sh','--only=semgrep'])
(fixture/'.swarms/streams/audit').mkdir(parents=True,exist_ok=True);(fixture/'.swarms/streams/audit/analysis.md').write_text('## Contracts consumed\n- unsupported:must-be-proven\n')
run('Unknown required contract passes',['bash','.claude/scripts/contract-tests.sh','audit'])
(fixture/'specs/active/900-audit.md').write_text('# Audit fixture\n## Acceptance criteria\nNo AC identifiers.\n## Notes\nFixture only.\n')
run('Zero-AC evidence emits invalid JSON but passes',['bash','.claude/scripts/collect-evidence.sh','900','--check-only'])
for p in (fixture/'verify').glob('*/evidence.json'):
 repros[-1]['evidence_bytes']=p.stat().st_size
(out/'failure-injection.json').write_text(json.dumps(repros,indent=2)+'\n')
print(json.dumps({'files':len(rows),'categories':manifest['categories'],'shellcheck_warning_diagnostics':len(json.loads((out/'shellcheck.json').read_text())),'reproductions':[(x['name'],x['exit_code']) for x in repros]}))
