#!/usr/bin/env bash
# Regression: installed boot hook injects hot context without volatile timestamps.
set -uo pipefail
ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"

pass=0; fail=0
check() { if [ "$2" -eq 0 ]; then pass=$((pass+1)); else fail=$((fail+1)); echo "  - $1"; fi; }


tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT
mkdir -p "$tmp/.claude/hooks" "$tmp/.claude/scripts" "$tmp/.claude/memory/.cache"
cp "$ROOT/.claude/hooks/session-start-context.sh" "$tmp/.claude/hooks/"

# Stub every script the boot hook shells out to; hot-cache writes a known hot.md.
for s in regen-skill-registry initiative-state memory-index memory-recall atlas-refresh; do
  printf '#!/usr/bin/env bash\nexit 0\n' > "$tmp/.claude/scripts/$s.sh"; chmod +x "$tmp/.claude/scripts/$s.sh"
done
cat > "$tmp/.claude/scripts/hot-cache.sh" <<EOF
#!/usr/bin/env bash
mkdir -p .claude/memory/.cache
{ echo "generated: SOME-TIMESTAMP-SENTINEL"; echo "IN-PROGRESS: T-777 do the thing"; echo "recent: T-776"; } > .claude/memory/.cache/hot.md
EOF
chmod +x "$tmp/.claude/scripts/hot-cache.sh"

# JUSTIFIED: Fixture hook stderr is excluded from captured JSON; subsequent assertions validate the actual context.
out=$(cd "$tmp" && bash .claude/hooks/session-start-context.sh </dev/null 2>/dev/null)

# The hot body must be injected...
printf '%s' "$out" | grep -q 'IN-PROGRESS: T-777'
check "boot injects the hot.md body (in-progress task)" $?
printf '%s' "$out" | grep -q '\[hot\]'
check "hot block is tagged [hot]" $?
# ...but the volatile generated: line must NOT be injected (cache-churn hygiene).
! printf '%s' "$out" | grep -q 'SOME-TIMESTAMP-SENTINEL'
check "the volatile 'generated:' timestamp line is NOT injected" $?

# And hot.md was actually (re)generated by the boot.
[ -f "$tmp/.claude/memory/.cache/hot.md" ]
check "boot regenerated .claude/memory/.cache/hot.md" $?

echo "passed: $pass"
echo "failed: $fail"
[ "$fail" -eq 0 ]
